export const USERS = [
    {
        firstName: 'Alice',
        lastName: 'Johnson',
        email: 'alice.johnson@example.com',
        phoneNumber: '+998911234567',
        password: 'Password12345',
    },
    {
        firstName: 'Bob',
        lastName: 'Smith',
        email: 'bob.smith@example.com',
        phoneNumber: '+998911234567',
        password: 'Password12345',
    },
    {
        firstName: 'Charlie',
        lastName: 'Davis',
        email: 'charlie.davis@example.com',
        phoneNumber: '+998911234567',
        password: 'Password12345',
    },
    {
        firstName: 'Diana',
        lastName: 'Miller',
        email: 'diana.miller@example.com',
        phoneNumber: '+998911234567',
        password: 'Password12345',
    },
];

export const CATEGORIES = [
    {
        name: 'Bicycle',
    },
    {
        name: 'Book',
    },
    {
        name: 'Beauty products',
    },
    {
        name: 'Clothes',
    },
    {
        name: 'Furniture',
    },
    {
        name: 'Musical instruments',
    },
    {
        name: 'Electronic items',
    },
    {
        name: 'Sports equipment',
    },
    {
        name: 'Tools',
    },
    {
        name: 'Other',
    },
];

export const ITEMS_AUCTION = [
    {
        title: 'Mountain Bike',
        description: 'A used but well-maintained mountain bike.',
        category: 'Bicycle',
        ownerPhone: '+998911234567',
        status: 'ACTIVE',
        participants: [],
        address: '123 Main St, Cityville',
        duration: 1,
        type: 'AUCTION',
        isClaimAllowed: false,
        isTransactionAllowed: false,
    },
    {
        title: 'Electric Guitar',
        description: 'Fender electric guitar in good condition.',
        category: 'Musical instruments',
        ownerPhone: '+998911234567',
        status: 'ACTIVE',
        participants: [],
        address: '456 Rock St, Townsville',
        duration: 1,
        type: 'AUCTION',
        isClaimAllowed: false,
        isTransactionAllowed: false,
    },
    {
        title: 'Laptop',
        description: '15-inch gaming laptop with a powerful GPU.',
        category: 'Electronic items',
        ownerPhone: '+998911234567',
        status: 'ACTIVE',
        participants: [],
        address: '789 Tech St, Metro City',
        duration: 1,
        type: 'AUCTION',
        isClaimAllowed: false,
        isTransactionAllowed: false,
    },
    {
        title: 'Treadmill',
        description: 'Almost new treadmill with digital display.',
        category: 'Sports equipment',
        ownerPhone: '+998911234567',
        status: 'ACTIVE',
        participants: [],
        address: '321 Fitness St, FitCity',
        duration: 1,
        type: 'AUCTION',
        isClaimAllowed: false,
        isTransactionAllowed: false,
    },
    {
        title: 'Bookshelf',
        description: 'Wooden bookshelf with five shelves.',
        category: 'Furniture',
        ownerPhone: '+998911234567',
        status: 'ACTIVE',
        participants: [],
        address: '567 Oak St, Riverside',
        duration: 1,
        type: 'AUCTION',
        isClaimAllowed: false,
        isTransactionAllowed: false,
    },
    {
        title: 'Wrench Set',
        description: 'Professional-grade wrench set.',
        category: 'Tools',
        ownerPhone: '+998911234567',
        status: 'ACTIVE',
        participants: [],
        address: '101 Tool St, Mechanic City',
        duration: 1,
        type: 'AUCTION',
        isClaimAllowed: false,
        isTransactionAllowed: false,
    },
    {
        title: 'Makeup Kit',
        description: 'Complete makeup set from a premium brand.',
        category: 'Beauty products',
        ownerPhone: '+998911234567',
        status: 'ACTIVE',
        participants: [],
        address: '202 Glam St, Fashion City',
        duration: 1,
        type: 'AUCTION',
        isClaimAllowed: false,
        isTransactionAllowed: false,
    },
    {
        title: 'Soccer Ball',
        description: 'Official size and weight soccer ball.',
        category: 'Sports equipment',
        ownerPhone: '+998911234567',
        status: 'ACTIVE',
        participants: [],
        address: '303 Soccer St, Sports Town',
        duration: 1,
        type: 'AUCTION',
        isClaimAllowed: false,
        isTransactionAllowed: false,
    },
    {
        title: 'Winter Jacket',
        description: 'Warm winter jacket, waterproof.',
        category: 'Clothes',
        ownerPhone: '+998911234567',
        status: 'ACTIVE',
        participants: [],
        address: '404 Fashion St, Cozy City',
        duration: 1,
        type: 'AUCTION',
        isClaimAllowed: false,
        isTransactionAllowed: false,
    },
    {
        title: 'Novel Collection',
        description: 'Set of 10 classic novels.',
        category: 'Book',
        ownerPhone: '+998911234567',
        status: 'ACTIVE',
        participants: [],
        address: '505 Library St, Booktown',
        duration: 1,
        type: 'AUCTION',
        isClaimAllowed: false,
        isTransactionAllowed: false,
    },
    {
        title: 'Drill Machine',
        description:
            'Heavy-duty drill machine, suitable for home and professional use.',
        category: 'Tools',
        ownerPhone: '+998911234567',
        status: 'ACTIVE',
        participants: [],
        address: '606 Workshop St, Handy Town',
        duration: 1,
        type: 'AUCTION',
        isClaimAllowed: false,
        isTransactionAllowed: false,
    },
    {
        title: 'Bluetooth Speaker',
        description: 'Portable Bluetooth speaker with deep bass.',
        category: 'Electronic items',
        ownerPhone: '+998911234567',
        status: 'ACTIVE',
        participants: [],
        address: '707 Sound St, Music City',
        duration: 1,
        type: 'AUCTION',
        isClaimAllowed: false,
        isTransactionAllowed: false,
    },
];

export const ITEMS_FIRST_BID = [
    {
        title: 'Desk Lamp',
        description:
            'Adjustable LED desk lamp with multiple brightness levels.',
        category: 'Electronic items',
        ownerPhone: '+998911234567',
        status: 'ACTIVE',
        participants: [],
        address: '101 Light St, Home City',
        duration: 0,
        type: 'FIRST_BID',
        isClaimAllowed: false,
        isTransactionAllowed: false,
    },
    {
        title: 'Hiking Backpack',
        description: 'Durable hiking backpack with multiple compartments.',
        category: 'Sports equipment',
        ownerPhone: '+998911234567',
        status: 'ACTIVE',
        participants: [],
        address: '202 Adventure St, Nature Town',
        duration: 0,
        type: 'FIRST_BID',
        isClaimAllowed: false,
        isTransactionAllowed: false,
    },
    {
        title: 'Dining Table',
        description: 'Wooden dining table with a modern finish.',
        category: 'Furniture',
        ownerPhone: '+998911234567',
        status: 'ACTIVE',
        participants: [],
        address: '303 Family St, Cozy City',
        duration: 0,
        type: 'FIRST_BID',
        isClaimAllowed: false,
        isTransactionAllowed: false,
    },
    {
        title: 'Hair Dryer',
        description:
            'Compact and powerful hair dryer with multiple heat settings.',
        category: 'Beauty products',
        ownerPhone: '+998911234567',
        status: 'ACTIVE',
        participants: [],
        address: '404 Style St, Fashion City',
        duration: 0,
        type: 'FIRST_BID',
        isClaimAllowed: false,
        isTransactionAllowed: false,
    },
    {
        title: 'Yoga Mat',
        description: 'Non-slip yoga mat, perfect for home workouts.',
        category: 'Sports equipment',
        ownerPhone: '+998911234567',
        status: 'ACTIVE',
        participants: [],
        address: '505 Wellness St, Fit Town',
        duration: 0,
        type: 'FIRST_BID',
        isClaimAllowed: false,
        isTransactionAllowed: false,
    },
    {
        title: 'Winter Gloves',
        description: 'Thermal winter gloves for extreme cold conditions.',
        category: 'Clothes',
        ownerPhone: '+998911234567',
        status: 'ACTIVE',
        participants: [],
        address: '606 Warm St, Snow City',
        duration: 0,
        type: 'FIRST_BID',
        isClaimAllowed: false,
        isTransactionAllowed: false,
    },
    {
        title: 'Toolbox',
        description: 'Complete set of essential hand tools.',
        category: 'Tools',
        ownerPhone: '+998911234567',
        status: 'ACTIVE',
        participants: [],
        address: '707 Work St, Handy City',
        duration: 0,
        type: 'FIRST_BID',
        isClaimAllowed: false,
        isTransactionAllowed: false,
    },
    {
        title: 'Coffee Maker',
        description: 'Automatic coffee maker with multiple brew settings.',
        category: 'Electronic items',
        ownerPhone: '+998911234567',
        status: 'ACTIVE',
        participants: [],
        address: '808 Brew St, Cafe Town',
        duration: 0,
        type: 'FIRST_BID',
        isClaimAllowed: false,
        isTransactionAllowed: false,
    },
];
